/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_on = 4,
  anon_sym__ = 5,
  anon_sym_id = 6,
  sym_property_value = 7,
  sym_identifier = 8,
  aux_sym_string_token1 = 9,
  aux_sym_string_token2 = 10,
  sym__newline = 11,
  sym__indent = 12,
  sym__dedent = 13,
  sym__break = 14,
  sym_source_file = 15,
  sym__rule = 16,
  sym_root_rule = 17,
  sym_class_rule = 18,
  sym__rule_body = 19,
  sym__declaration = 20,
  sym_widget_declaration = 21,
  sym_property = 22,
  sym_event_binding = 23,
  sym_id_declaration = 24,
  sym_string = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym__rule_body_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_on] = "on",
  [anon_sym__] = "_",
  [anon_sym_id] = "id",
  [sym_property_value] = "property_value",
  [sym_identifier] = "identifier",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__break] = "_break",
  [sym_source_file] = "source_file",
  [sym__rule] = "_rule",
  [sym_root_rule] = "root_rule",
  [sym_class_rule] = "class_rule",
  [sym__rule_body] = "_rule_body",
  [sym__declaration] = "_declaration",
  [sym_widget_declaration] = "widget_declaration",
  [sym_property] = "property",
  [sym_event_binding] = "event_binding",
  [sym_id_declaration] = "id_declaration",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__rule_body_repeat1] = "_rule_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_on] = anon_sym_on,
  [anon_sym__] = anon_sym__,
  [anon_sym_id] = anon_sym_id,
  [sym_property_value] = sym_property_value,
  [sym_identifier] = sym_identifier,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__break] = sym__break,
  [sym_source_file] = sym_source_file,
  [sym__rule] = sym__rule,
  [sym_root_rule] = sym_root_rule,
  [sym_class_rule] = sym_class_rule,
  [sym__rule_body] = sym__rule_body,
  [sym__declaration] = sym__declaration,
  [sym_widget_declaration] = sym_widget_declaration,
  [sym_property] = sym_property,
  [sym_event_binding] = sym_event_binding,
  [sym_id_declaration] = sym_id_declaration,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__rule_body_repeat1] = aux_sym__rule_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_id] = {
    .visible = true,
    .named = false,
  },
  [sym_property_value] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__break] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__rule] = {
    .visible = false,
    .named = true,
  },
  [sym_root_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_class_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__rule_body] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_widget_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_event_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_id_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__rule_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_event = 1,
  field_handler = 2,
  field_name = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_event] = "event",
  [field_handler] = "handler",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 2},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_event, 2},
    {field_handler, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '\'', 2,
        ':', 9,
        '<', 10,
        '>', 11,
        '_', 14,
        'i', 3,
        'o', 5,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(2);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_on);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_id);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_property_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 7, .external_lex_state = 2},
  [2] = {.lex_state = 4, .external_lex_state = 3},
  [3] = {.lex_state = 4, .external_lex_state = 3},
  [4] = {.lex_state = 4, .external_lex_state = 3},
  [5] = {.lex_state = 4, .external_lex_state = 3},
  [6] = {.lex_state = 4, .external_lex_state = 3},
  [7] = {.lex_state = 7, .external_lex_state = 2},
  [8] = {.lex_state = 7, .external_lex_state = 2},
  [9] = {.lex_state = 7, .external_lex_state = 4},
  [10] = {.lex_state = 7, .external_lex_state = 4},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 4, .external_lex_state = 5},
  [15] = {.lex_state = 4, .external_lex_state = 5},
  [16] = {.lex_state = 4, .external_lex_state = 5},
  [17] = {.lex_state = 4, .external_lex_state = 5},
  [18] = {.lex_state = 4, .external_lex_state = 3},
  [19] = {.lex_state = 7, .external_lex_state = 2},
  [20] = {.lex_state = 7, .external_lex_state = 2},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 6, .external_lex_state = 6},
  [23] = {.lex_state = 7, .external_lex_state = 2},
  [24] = {.lex_state = 4, .external_lex_state = 3},
  [25] = {.lex_state = 7, .external_lex_state = 2},
  [26] = {.lex_state = 4, .external_lex_state = 3},
  [27] = {.lex_state = 4, .external_lex_state = 3},
  [28] = {.lex_state = 7, .external_lex_state = 2},
  [29] = {.lex_state = 4, .external_lex_state = 3},
  [30] = {.lex_state = 4, .external_lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_id] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__break] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym__rule] = STATE(7),
    [sym_root_rule] = STATE(7),
    [sym_class_rule] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym__break] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(11), 1,
      anon_sym_on,
    ACTIONS(13), 1,
      anon_sym_id,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__dedent,
    STATE(3), 6,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [21] = 5,
    ACTIONS(11), 1,
      anon_sym_on,
    ACTIONS(13), 1,
      anon_sym_id,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__dedent,
    STATE(6), 6,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [42] = 5,
    ACTIONS(11), 1,
      anon_sym_on,
    ACTIONS(13), 1,
      anon_sym_id,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym__dedent,
    STATE(5), 6,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [63] = 5,
    ACTIONS(11), 1,
      anon_sym_on,
    ACTIONS(13), 1,
      anon_sym_id,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym__dedent,
    STATE(6), 6,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [84] = 5,
    ACTIONS(25), 1,
      anon_sym_on,
    ACTIONS(28), 1,
      anon_sym_id,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(34), 1,
      sym__dedent,
    STATE(6), 6,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [105] = 5,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      sym__break,
    STATE(8), 4,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
      aux_sym_source_file_repeat1,
  [124] = 5,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym__break,
    STATE(8), 4,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
      aux_sym_source_file_repeat1,
  [143] = 4,
    ACTIONS(53), 1,
      sym__newline,
    ACTIONS(55), 1,
      sym__indent,
    STATE(25), 1,
      sym__rule_body,
    ACTIONS(51), 4,
      sym__break,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [159] = 4,
    ACTIONS(55), 1,
      sym__indent,
    ACTIONS(59), 1,
      sym__newline,
    STATE(19), 1,
      sym__rule_body,
    ACTIONS(57), 4,
      sym__break,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [175] = 4,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(23), 3,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
  [190] = 4,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    STATE(23), 3,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
  [205] = 3,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(23), 3,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
  [217] = 2,
    ACTIONS(65), 2,
      sym__newline,
      sym__dedent,
    ACTIONS(63), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [227] = 3,
    ACTIONS(69), 1,
      sym__newline,
    ACTIONS(71), 1,
      sym__dedent,
    ACTIONS(67), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [239] = 3,
    ACTIONS(75), 1,
      sym__newline,
    ACTIONS(77), 1,
      sym__dedent,
    ACTIONS(73), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [251] = 3,
    ACTIONS(81), 1,
      sym__newline,
    ACTIONS(83), 1,
      sym__dedent,
    ACTIONS(79), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [263] = 2,
    ACTIONS(87), 1,
      sym__dedent,
    ACTIONS(85), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [272] = 1,
    ACTIONS(89), 4,
      sym__break,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [279] = 1,
    ACTIONS(91), 4,
      sym__break,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [286] = 3,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(16), 1,
      sym_string,
    ACTIONS(95), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [297] = 3,
    ACTIONS(97), 1,
      sym_property_value,
    ACTIONS(101), 1,
      sym__indent,
    ACTIONS(99), 2,
      sym__newline,
      sym__dedent,
  [308] = 1,
    ACTIONS(40), 4,
      sym__break,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [315] = 2,
    ACTIONS(105), 1,
      sym__dedent,
    ACTIONS(103), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [324] = 1,
    ACTIONS(107), 4,
      sym__break,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [331] = 2,
    ACTIONS(111), 1,
      sym__dedent,
    ACTIONS(109), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [340] = 2,
    ACTIONS(115), 1,
      sym__dedent,
    ACTIONS(113), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [349] = 1,
    ACTIONS(117), 4,
      sym__break,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [356] = 2,
    ACTIONS(121), 1,
      sym__dedent,
    ACTIONS(119), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [365] = 2,
    ACTIONS(125), 1,
      sym__dedent,
    ACTIONS(123), 3,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [374] = 1,
    ACTIONS(127), 1,
      anon_sym_COLON,
  [378] = 1,
    ACTIONS(129), 1,
      sym_identifier,
  [382] = 1,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
  [386] = 1,
    ACTIONS(133), 1,
      anon_sym_COLON,
  [390] = 1,
    ACTIONS(135), 1,
      sym_identifier,
  [394] = 1,
    ACTIONS(137), 1,
      anon_sym_COLON,
  [398] = 1,
    ACTIONS(139), 1,
      anon_sym_COLON,
  [402] = 1,
    ACTIONS(141), 1,
      anon_sym_GT,
  [406] = 1,
    ACTIONS(143), 1,
      anon_sym_COLON,
  [410] = 1,
    ACTIONS(145), 1,
      sym_property_value,
  [414] = 1,
    ACTIONS(147), 1,
      anon_sym__,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 63,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 124,
  [SMALL_STATE(9)] = 143,
  [SMALL_STATE(10)] = 159,
  [SMALL_STATE(11)] = 175,
  [SMALL_STATE(12)] = 190,
  [SMALL_STATE(13)] = 205,
  [SMALL_STATE(14)] = 217,
  [SMALL_STATE(15)] = 227,
  [SMALL_STATE(16)] = 239,
  [SMALL_STATE(17)] = 251,
  [SMALL_STATE(18)] = 263,
  [SMALL_STATE(19)] = 272,
  [SMALL_STATE(20)] = 279,
  [SMALL_STATE(21)] = 286,
  [SMALL_STATE(22)] = 297,
  [SMALL_STATE(23)] = 308,
  [SMALL_STATE(24)] = 315,
  [SMALL_STATE(25)] = 324,
  [SMALL_STATE(26)] = 331,
  [SMALL_STATE(27)] = 340,
  [SMALL_STATE(28)] = 349,
  [SMALL_STATE(29)] = 356,
  [SMALL_STATE(30)] = 365,
  [SMALL_STATE(31)] = 374,
  [SMALL_STATE(32)] = 378,
  [SMALL_STATE(33)] = 382,
  [SMALL_STATE(34)] = 386,
  [SMALL_STATE(35)] = 390,
  [SMALL_STATE(36)] = 394,
  [SMALL_STATE(37)] = 398,
  [SMALL_STATE(38)] = 402,
  [SMALL_STATE(39)] = 406,
  [SMALL_STATE(40)] = 410,
  [SMALL_STATE(41)] = 414,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_rule, 2, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 4, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 4),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_declaration, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_declaration, 3, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_event_binding, 5, 0, 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_binding, 5, 0, 5),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_declaration, 4, 0, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_declaration, 4, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 5, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_body, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_widget_declaration, 3, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_widget_declaration, 3, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_rule, 3, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_widget_declaration, 4, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_widget_declaration, 4, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_body, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_widget_declaration, 5, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_widget_declaration, 5, 0, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_event_binding, 6, 0, 5),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_binding, 6, 0, 5),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [131] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token__break = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__break] = sym__break,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
  },
  [2] = {
    [ts_external_token__break] = true,
  },
  [3] = {
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__break] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_kivy_external_scanner_create(void);
void tree_sitter_kivy_external_scanner_destroy(void *);
bool tree_sitter_kivy_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_kivy_external_scanner_serialize(void *, char *);
void tree_sitter_kivy_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kivy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_kivy_external_scanner_create,
      tree_sitter_kivy_external_scanner_destroy,
      tree_sitter_kivy_external_scanner_scan,
      tree_sitter_kivy_external_scanner_serialize,
      tree_sitter_kivy_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "kivy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
