/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 118
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_import = 1,
  anon_sym_set = 2,
  anon_sym_kivy = 3,
  aux_sym_directive_value_token1 = 4,
  anon_sym_COLON = 5,
  anon_sym_LT = 6,
  anon_sym_AT = 7,
  anon_sym_PLUS = 8,
  anon_sym_GT = 9,
  anon_sym_canvas_DOTbefore = 10,
  anon_sym_canvas_DOTafter = 11,
  anon_sym_canvas = 12,
  anon_sym_Clear = 13,
  anon_sym_PushMatrix = 14,
  anon_sym_PopMatrix = 15,
  anon_sym_on = 16,
  anon_sym__ = 17,
  anon_sym_id = 18,
  sym_identifier = 19,
  aux_sym_string_token1 = 20,
  aux_sym_string_token2 = 21,
  sym__newline = 22,
  sym__indent = 23,
  sym__dedent = 24,
  sym__break = 25,
  sym__directive_start = 26,
  sym_source_file = 27,
  sym__directive = 28,
  sym_import_directive = 29,
  sym_set_directive = 30,
  sym_kivy_directive = 31,
  sym_directive_value = 32,
  sym__rule = 33,
  sym_root_rule = 34,
  sym_class_rule = 35,
  sym__rule_body = 36,
  sym__canvas_header = 37,
  sym_canvas_block = 38,
  sym__canvas_atom = 39,
  sym__declaration = 40,
  sym_widget_declaration = 41,
  sym_property = 42,
  sym_event_binding = 43,
  sym_id_declaration = 44,
  sym_property_value = 45,
  sym_string = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_class_rule_repeat1 = 48,
  aux_sym__rule_body_repeat1 = 49,
  aux_sym_canvas_block_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_import] = "import",
  [anon_sym_set] = "set",
  [anon_sym_kivy] = "kivy",
  [aux_sym_directive_value_token1] = "directive_value_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_AT] = "@",
  [anon_sym_PLUS] = "+",
  [anon_sym_GT] = ">",
  [anon_sym_canvas_DOTbefore] = "canvas.before",
  [anon_sym_canvas_DOTafter] = "canvas.after",
  [anon_sym_canvas] = "canvas",
  [anon_sym_Clear] = "Clear",
  [anon_sym_PushMatrix] = "PushMatrix",
  [anon_sym_PopMatrix] = "PopMatrix",
  [anon_sym_on] = "on",
  [anon_sym__] = "_",
  [anon_sym_id] = "id",
  [sym_identifier] = "identifier",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__break] = "_break",
  [sym__directive_start] = "_directive_start",
  [sym_source_file] = "source_file",
  [sym__directive] = "_directive",
  [sym_import_directive] = "import_directive",
  [sym_set_directive] = "set_directive",
  [sym_kivy_directive] = "kivy_directive",
  [sym_directive_value] = "directive_value",
  [sym__rule] = "_rule",
  [sym_root_rule] = "root_rule",
  [sym_class_rule] = "class_rule",
  [sym__rule_body] = "_rule_body",
  [sym__canvas_header] = "_canvas_header",
  [sym_canvas_block] = "canvas_block",
  [sym__canvas_atom] = "_canvas_atom",
  [sym__declaration] = "_declaration",
  [sym_widget_declaration] = "widget_declaration",
  [sym_property] = "property",
  [sym_event_binding] = "event_binding",
  [sym_id_declaration] = "id_declaration",
  [sym_property_value] = "property_value",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_class_rule_repeat1] = "class_rule_repeat1",
  [aux_sym__rule_body_repeat1] = "_rule_body_repeat1",
  [aux_sym_canvas_block_repeat1] = "canvas_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_kivy] = anon_sym_kivy,
  [aux_sym_directive_value_token1] = aux_sym_directive_value_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_canvas_DOTbefore] = anon_sym_canvas_DOTbefore,
  [anon_sym_canvas_DOTafter] = anon_sym_canvas_DOTafter,
  [anon_sym_canvas] = anon_sym_canvas,
  [anon_sym_Clear] = anon_sym_Clear,
  [anon_sym_PushMatrix] = anon_sym_PushMatrix,
  [anon_sym_PopMatrix] = anon_sym_PopMatrix,
  [anon_sym_on] = anon_sym_on,
  [anon_sym__] = anon_sym__,
  [anon_sym_id] = anon_sym_id,
  [sym_identifier] = sym_identifier,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__break] = sym__break,
  [sym__directive_start] = sym__directive_start,
  [sym_source_file] = sym_source_file,
  [sym__directive] = sym__directive,
  [sym_import_directive] = sym_import_directive,
  [sym_set_directive] = sym_set_directive,
  [sym_kivy_directive] = sym_kivy_directive,
  [sym_directive_value] = sym_directive_value,
  [sym__rule] = sym__rule,
  [sym_root_rule] = sym_root_rule,
  [sym_class_rule] = sym_class_rule,
  [sym__rule_body] = sym__rule_body,
  [sym__canvas_header] = sym__canvas_header,
  [sym_canvas_block] = sym_canvas_block,
  [sym__canvas_atom] = sym__canvas_atom,
  [sym__declaration] = sym__declaration,
  [sym_widget_declaration] = sym_widget_declaration,
  [sym_property] = sym_property,
  [sym_event_binding] = sym_event_binding,
  [sym_id_declaration] = sym_id_declaration,
  [sym_property_value] = sym_property_value,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_class_rule_repeat1] = aux_sym_class_rule_repeat1,
  [aux_sym__rule_body_repeat1] = aux_sym__rule_body_repeat1,
  [aux_sym_canvas_block_repeat1] = aux_sym_canvas_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_kivy] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_canvas_DOTbefore] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_canvas_DOTafter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_canvas] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Clear] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PushMatrix] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PopMatrix] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_id] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__break] = {
    .visible = false,
    .named = true,
  },
  [sym__directive_start] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__directive] = {
    .visible = false,
    .named = true,
  },
  [sym_import_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_set_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_kivy_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_value] = {
    .visible = true,
    .named = true,
  },
  [sym__rule] = {
    .visible = false,
    .named = true,
  },
  [sym_root_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_class_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__rule_body] = {
    .visible = false,
    .named = true,
  },
  [sym__canvas_header] = {
    .visible = false,
    .named = true,
  },
  [sym_canvas_block] = {
    .visible = true,
    .named = true,
  },
  [sym__canvas_atom] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_widget_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_event_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_id_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_property_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__rule_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_canvas_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_base = 2,
  field_event = 3,
  field_handler = 4,
  field_module = 5,
  field_name = 6,
  field_value = 7,
  field_version = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_base] = "base",
  [field_event] = "event",
  [field_handler] = "handler",
  [field_module] = "module",
  [field_name] = "name",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 3},
  [14] = {.index = 21, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_version, 2},
  [2] =
    {field_name, 1},
  [3] =
    {field_alias, 2},
    {field_module, 3},
  [5] =
    {field_name, 2},
    {field_value, 3},
  [7] =
    {field_base, 1},
  [8] =
    {field_base, 2},
  [9] =
    {field_base, 0, .inherited = true},
    {field_base, 1, .inherited = true},
  [11] =
    {field_base, 2},
    {field_base, 3, .inherited = true},
  [13] =
    {field_base, 3},
    {field_name, 1},
  [15] =
    {field_name, 2},
  [16] =
    {field_name, 0},
    {field_value, 2},
  [18] =
    {field_base, 3},
    {field_base, 4, .inherited = true},
    {field_name, 1},
  [21] =
    {field_event, 2},
    {field_handler, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 19,
  [36] = 17,
  [37] = 20,
  [38] = 16,
  [39] = 39,
  [40] = 40,
  [41] = 18,
  [42] = 42,
  [43] = 24,
  [44] = 27,
  [45] = 25,
  [46] = 21,
  [47] = 28,
  [48] = 30,
  [49] = 29,
  [50] = 22,
  [51] = 23,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 64,
  [70] = 70,
  [71] = 70,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 83,
  [85] = 85,
  [86] = 81,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 88,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 97,
  [114] = 98,
  [115] = 99,
  [116] = 101,
  [117] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '"', 1,
        '\'', 2,
        '+', 61,
        ':', 58,
        '<', 59,
        '>', 62,
        '@', 60,
        'C', 25,
        'P', 28,
        '_', 75,
        'c', 8,
        'i', 13,
        'k', 22,
        'o', 26,
        's', 14,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(107);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(106);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'C') ADVANCE(90);
      if (lookahead == 'P') ADVANCE(93);
      if (lookahead == 'c') ADVANCE(82);
      if (lookahead == 'i') ADVANCE(85);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 4:
      if (lookahead == 'M') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'M') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'b') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(82);
      if (lookahead == 'i') ADVANCE(85);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(76);
      if (lookahead == 'm') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'h') ADVANCE(5);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(31);
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(4);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 46:
      if (lookahead == 'v') ADVANCE(50);
      END_STATE();
    case 47:
      if (lookahead == 'v') ADVANCE(9);
      END_STATE();
    case 48:
      if (lookahead == 'x') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'x') ADVANCE(69);
      END_STATE();
    case 50:
      if (lookahead == 'y') ADVANCE(56);
      END_STATE();
    case 51:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(57);
      END_STATE();
    case 52:
      if (eof) ADVANCE(53);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(2);
      if (lookahead == '<') ADVANCE(59);
      if (lookahead == '>') ADVANCE(62);
      if (lookahead == '@') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_kivy);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_directive_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_canvas_DOTbefore);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_canvas_DOTafter);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_canvas);
      if (lookahead == '.') ADVANCE(7);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_canvas);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_Clear);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_Clear);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_PushMatrix);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_PushMatrix);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PopMatrix);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_PopMatrix);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_on);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_id);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(94);
      if (lookahead == 'u') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 52, .external_lex_state = 2},
  [2] = {.lex_state = 3, .external_lex_state = 3},
  [3] = {.lex_state = 3, .external_lex_state = 3},
  [4] = {.lex_state = 3, .external_lex_state = 3},
  [5] = {.lex_state = 3, .external_lex_state = 3},
  [6] = {.lex_state = 3, .external_lex_state = 3},
  [7] = {.lex_state = 12, .external_lex_state = 3},
  [8] = {.lex_state = 12, .external_lex_state = 3},
  [9] = {.lex_state = 12, .external_lex_state = 3},
  [10] = {.lex_state = 12, .external_lex_state = 3},
  [11] = {.lex_state = 12, .external_lex_state = 3},
  [12] = {.lex_state = 12, .external_lex_state = 3},
  [13] = {.lex_state = 12, .external_lex_state = 3},
  [14] = {.lex_state = 52, .external_lex_state = 2},
  [15] = {.lex_state = 52, .external_lex_state = 2},
  [16] = {.lex_state = 3, .external_lex_state = 4},
  [17] = {.lex_state = 3, .external_lex_state = 4},
  [18] = {.lex_state = 3, .external_lex_state = 4},
  [19] = {.lex_state = 3, .external_lex_state = 4},
  [20] = {.lex_state = 3, .external_lex_state = 4},
  [21] = {.lex_state = 3, .external_lex_state = 3},
  [22] = {.lex_state = 3, .external_lex_state = 3},
  [23] = {.lex_state = 3, .external_lex_state = 3},
  [24] = {.lex_state = 3, .external_lex_state = 3},
  [25] = {.lex_state = 3, .external_lex_state = 3},
  [26] = {.lex_state = 3, .external_lex_state = 3},
  [27] = {.lex_state = 3, .external_lex_state = 3},
  [28] = {.lex_state = 3, .external_lex_state = 3},
  [29] = {.lex_state = 3, .external_lex_state = 3},
  [30] = {.lex_state = 3, .external_lex_state = 3},
  [31] = {.lex_state = 52, .external_lex_state = 5},
  [32] = {.lex_state = 52, .external_lex_state = 5},
  [33] = {.lex_state = 52, .external_lex_state = 5},
  [34] = {.lex_state = 52, .external_lex_state = 5},
  [35] = {.lex_state = 12, .external_lex_state = 4},
  [36] = {.lex_state = 12, .external_lex_state = 4},
  [37] = {.lex_state = 12, .external_lex_state = 4},
  [38] = {.lex_state = 12, .external_lex_state = 4},
  [39] = {.lex_state = 52, .external_lex_state = 5},
  [40] = {.lex_state = 52, .external_lex_state = 5},
  [41] = {.lex_state = 12, .external_lex_state = 4},
  [42] = {.lex_state = 52, .external_lex_state = 5},
  [43] = {.lex_state = 12, .external_lex_state = 3},
  [44] = {.lex_state = 12, .external_lex_state = 3},
  [45] = {.lex_state = 12, .external_lex_state = 3},
  [46] = {.lex_state = 12, .external_lex_state = 3},
  [47] = {.lex_state = 12, .external_lex_state = 3},
  [48] = {.lex_state = 12, .external_lex_state = 3},
  [49] = {.lex_state = 12, .external_lex_state = 3},
  [50] = {.lex_state = 12, .external_lex_state = 3},
  [51] = {.lex_state = 12, .external_lex_state = 3},
  [52] = {.lex_state = 52},
  [53] = {.lex_state = 52},
  [54] = {.lex_state = 52, .external_lex_state = 2},
  [55] = {.lex_state = 52, .external_lex_state = 2},
  [56] = {.lex_state = 52, .external_lex_state = 2},
  [57] = {.lex_state = 52, .external_lex_state = 2},
  [58] = {.lex_state = 52, .external_lex_state = 2},
  [59] = {.lex_state = 52, .external_lex_state = 2},
  [60] = {.lex_state = 52, .external_lex_state = 2},
  [61] = {.lex_state = 52, .external_lex_state = 2},
  [62] = {.lex_state = 52, .external_lex_state = 2},
  [63] = {.lex_state = 52, .external_lex_state = 2},
  [64] = {.lex_state = 51, .external_lex_state = 6},
  [65] = {.lex_state = 52, .external_lex_state = 2},
  [66] = {.lex_state = 52, .external_lex_state = 2},
  [67] = {.lex_state = 52, .external_lex_state = 2},
  [68] = {.lex_state = 52},
  [69] = {.lex_state = 51, .external_lex_state = 6},
  [70] = {.lex_state = 52},
  [71] = {.lex_state = 52},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 52},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 51},
  [81] = {.lex_state = 0, .external_lex_state = 7},
  [82] = {.lex_state = 51},
  [83] = {.lex_state = 51},
  [84] = {.lex_state = 51},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 7},
  [87] = {.lex_state = 51},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0, .external_lex_state = 8},
  [90] = {.lex_state = 52},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 52},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 52},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 52},
  [102] = {.lex_state = 0, .external_lex_state = 8},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 52},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 52},
  [110] = {.lex_state = 0, .external_lex_state = 8},
  [111] = {.lex_state = 0, .external_lex_state = 8},
  [112] = {.lex_state = 0, .external_lex_state = 8},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 52},
  [117] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_kivy] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_canvas_DOTbefore] = ACTIONS(1),
    [anon_sym_canvas_DOTafter] = ACTIONS(1),
    [anon_sym_canvas] = ACTIONS(1),
    [anon_sym_Clear] = ACTIONS(1),
    [anon_sym_PushMatrix] = ACTIONS(1),
    [anon_sym_PopMatrix] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_id] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__break] = ACTIONS(1),
    [sym__directive_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(104),
    [sym__directive] = STATE(15),
    [sym_import_directive] = STATE(15),
    [sym_set_directive] = STATE(15),
    [sym_kivy_directive] = STATE(15),
    [sym__rule] = STATE(15),
    [sym_root_rule] = STATE(15),
    [sym_class_rule] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym__break] = ACTIONS(9),
    [sym__directive_start] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(15), 1,
      anon_sym_canvas,
    ACTIONS(19), 1,
      anon_sym_on,
    ACTIONS(21), 1,
      anon_sym_id,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym__dedent,
    STATE(115), 1,
      sym__canvas_header,
    ACTIONS(13), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(17), 3,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
    STATE(3), 8,
      sym_canvas_block,
      sym__canvas_atom,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym_canvas_block_repeat1,
  [38] = 9,
    ACTIONS(15), 1,
      anon_sym_canvas,
    ACTIONS(19), 1,
      anon_sym_on,
    ACTIONS(21), 1,
      anon_sym_id,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym__dedent,
    STATE(115), 1,
      sym__canvas_header,
    ACTIONS(13), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(17), 3,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
    STATE(5), 8,
      sym_canvas_block,
      sym__canvas_atom,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym_canvas_block_repeat1,
  [76] = 9,
    ACTIONS(15), 1,
      anon_sym_canvas,
    ACTIONS(19), 1,
      anon_sym_on,
    ACTIONS(21), 1,
      anon_sym_id,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym__dedent,
    STATE(115), 1,
      sym__canvas_header,
    ACTIONS(13), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(17), 3,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
    STATE(6), 8,
      sym_canvas_block,
      sym__canvas_atom,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym_canvas_block_repeat1,
  [114] = 9,
    ACTIONS(34), 1,
      anon_sym_canvas,
    ACTIONS(40), 1,
      anon_sym_on,
    ACTIONS(43), 1,
      anon_sym_id,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(49), 1,
      sym__dedent,
    STATE(115), 1,
      sym__canvas_header,
    ACTIONS(31), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(37), 3,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
    STATE(5), 8,
      sym_canvas_block,
      sym__canvas_atom,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym_canvas_block_repeat1,
  [152] = 9,
    ACTIONS(15), 1,
      anon_sym_canvas,
    ACTIONS(19), 1,
      anon_sym_on,
    ACTIONS(21), 1,
      anon_sym_id,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym__dedent,
    STATE(115), 1,
      sym__canvas_header,
    ACTIONS(13), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(17), 3,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
    STATE(5), 8,
      sym_canvas_block,
      sym__canvas_atom,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym_canvas_block_repeat1,
  [190] = 8,
    ACTIONS(56), 1,
      anon_sym_canvas,
    ACTIONS(59), 1,
      anon_sym_on,
    ACTIONS(62), 1,
      anon_sym_id,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(68), 1,
      sym__dedent,
    STATE(99), 1,
      sym__canvas_header,
    ACTIONS(53), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    STATE(7), 7,
      sym_canvas_block,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [222] = 8,
    ACTIONS(72), 1,
      anon_sym_canvas,
    ACTIONS(74), 1,
      anon_sym_on,
    ACTIONS(76), 1,
      anon_sym_id,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      sym__dedent,
    STATE(99), 1,
      sym__canvas_header,
    ACTIONS(70), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    STATE(9), 7,
      sym_canvas_block,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [254] = 8,
    ACTIONS(72), 1,
      anon_sym_canvas,
    ACTIONS(74), 1,
      anon_sym_on,
    ACTIONS(76), 1,
      anon_sym_id,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      sym__dedent,
    STATE(99), 1,
      sym__canvas_header,
    ACTIONS(70), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    STATE(7), 7,
      sym_canvas_block,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [286] = 8,
    ACTIONS(72), 1,
      anon_sym_canvas,
    ACTIONS(74), 1,
      anon_sym_on,
    ACTIONS(76), 1,
      anon_sym_id,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym__dedent,
    STATE(99), 1,
      sym__canvas_header,
    ACTIONS(70), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    STATE(11), 7,
      sym_canvas_block,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [318] = 8,
    ACTIONS(72), 1,
      anon_sym_canvas,
    ACTIONS(74), 1,
      anon_sym_on,
    ACTIONS(76), 1,
      anon_sym_id,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(86), 1,
      sym__dedent,
    STATE(99), 1,
      sym__canvas_header,
    ACTIONS(70), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    STATE(7), 7,
      sym_canvas_block,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [350] = 8,
    ACTIONS(72), 1,
      anon_sym_canvas,
    ACTIONS(74), 1,
      anon_sym_on,
    ACTIONS(76), 1,
      anon_sym_id,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(88), 1,
      sym__dedent,
    STATE(99), 1,
      sym__canvas_header,
    ACTIONS(70), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    STATE(13), 7,
      sym_canvas_block,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [382] = 8,
    ACTIONS(72), 1,
      anon_sym_canvas,
    ACTIONS(74), 1,
      anon_sym_on,
    ACTIONS(76), 1,
      anon_sym_id,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(90), 1,
      sym__dedent,
    STATE(99), 1,
      sym__canvas_header,
    ACTIONS(70), 2,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    STATE(7), 7,
      sym_canvas_block,
      sym__declaration,
      sym_widget_declaration,
      sym_property,
      sym_event_binding,
      sym_id_declaration,
      aux_sym__rule_body_repeat1,
  [414] = 6,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 1,
      anon_sym_LT,
    ACTIONS(97), 1,
      sym_identifier,
    ACTIONS(100), 1,
      sym__break,
    ACTIONS(103), 1,
      sym__directive_start,
    STATE(14), 8,
      sym__directive,
      sym_import_directive,
      sym_set_directive,
      sym_kivy_directive,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
      aux_sym_source_file_repeat1,
  [440] = 6,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym__directive_start,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      sym__break,
    STATE(14), 8,
      sym__directive,
      sym_import_directive,
      sym_set_directive,
      sym_kivy_directive,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
      aux_sym_source_file_repeat1,
  [466] = 2,
    ACTIONS(110), 4,
      sym__newline,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(112), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [482] = 2,
    ACTIONS(114), 4,
      sym__newline,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(116), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [498] = 3,
    ACTIONS(122), 1,
      sym__newline,
    ACTIONS(118), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(120), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [516] = 3,
    ACTIONS(128), 1,
      sym__newline,
    ACTIONS(124), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(126), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [534] = 3,
    ACTIONS(134), 1,
      sym__newline,
    ACTIONS(130), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(132), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [552] = 2,
    ACTIONS(136), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(138), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [567] = 2,
    ACTIONS(140), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(142), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [582] = 2,
    ACTIONS(144), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(146), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [597] = 2,
    ACTIONS(148), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(150), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [612] = 2,
    ACTIONS(152), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(154), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [627] = 2,
    ACTIONS(156), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(158), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [642] = 2,
    ACTIONS(160), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(162), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [657] = 2,
    ACTIONS(164), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(166), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [672] = 2,
    ACTIONS(168), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(170), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [687] = 2,
    ACTIONS(172), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(174), 7,
      anon_sym_canvas,
      anon_sym_Clear,
      anon_sym_PushMatrix,
      anon_sym_PopMatrix,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [702] = 4,
    ACTIONS(178), 1,
      sym__newline,
    ACTIONS(180), 1,
      sym__indent,
    STATE(60), 1,
      sym__rule_body,
    ACTIONS(176), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [719] = 4,
    ACTIONS(180), 1,
      sym__indent,
    ACTIONS(184), 1,
      sym__newline,
    STATE(66), 1,
      sym__rule_body,
    ACTIONS(182), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [736] = 4,
    ACTIONS(180), 1,
      sym__indent,
    ACTIONS(188), 1,
      sym__newline,
    STATE(62), 1,
      sym__rule_body,
    ACTIONS(186), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [753] = 4,
    ACTIONS(180), 1,
      sym__indent,
    ACTIONS(192), 1,
      sym__newline,
    STATE(63), 1,
      sym__rule_body,
    ACTIONS(190), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [770] = 3,
    ACTIONS(194), 1,
      sym__newline,
    ACTIONS(124), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(126), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [785] = 2,
    ACTIONS(114), 4,
      sym__newline,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(116), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [798] = 3,
    ACTIONS(196), 1,
      sym__newline,
    ACTIONS(130), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(132), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [813] = 2,
    ACTIONS(110), 4,
      sym__newline,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(112), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [826] = 4,
    ACTIONS(180), 1,
      sym__indent,
    ACTIONS(200), 1,
      sym__newline,
    STATE(54), 1,
      sym__rule_body,
    ACTIONS(198), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [843] = 4,
    ACTIONS(180), 1,
      sym__indent,
    ACTIONS(204), 1,
      sym__newline,
    STATE(67), 1,
      sym__rule_body,
    ACTIONS(202), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [860] = 3,
    ACTIONS(206), 1,
      sym__newline,
    ACTIONS(118), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(120), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [875] = 4,
    ACTIONS(180), 1,
      sym__indent,
    ACTIONS(210), 1,
      sym__newline,
    STATE(55), 1,
      sym__rule_body,
    ACTIONS(208), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [892] = 2,
    ACTIONS(148), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(150), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [904] = 2,
    ACTIONS(160), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(162), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [916] = 2,
    ACTIONS(152), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(154), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [928] = 2,
    ACTIONS(136), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(138), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [940] = 2,
    ACTIONS(164), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(166), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [952] = 2,
    ACTIONS(172), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(174), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [964] = 2,
    ACTIONS(168), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(170), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [976] = 2,
    ACTIONS(140), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(142), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [988] = 2,
    ACTIONS(144), 3,
      sym__dedent,
      anon_sym_canvas_DOTbefore,
      anon_sym_canvas_DOTafter,
    ACTIONS(146), 4,
      anon_sym_canvas,
      anon_sym_on,
      anon_sym_id,
      sym_identifier,
  [1000] = 4,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    STATE(61), 3,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
  [1015] = 4,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    STATE(61), 3,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
  [1030] = 1,
    ACTIONS(214), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1038] = 1,
    ACTIONS(216), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1046] = 1,
    ACTIONS(218), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1054] = 1,
    ACTIONS(220), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1062] = 1,
    ACTIONS(222), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1070] = 1,
    ACTIONS(224), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1078] = 1,
    ACTIONS(226), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1086] = 1,
    ACTIONS(92), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1094] = 1,
    ACTIONS(228), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1102] = 1,
    ACTIONS(230), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1110] = 4,
    ACTIONS(232), 1,
      aux_sym_directive_value_token1,
    ACTIONS(236), 1,
      sym__indent,
    STATE(37), 1,
      sym_property_value,
    ACTIONS(234), 2,
      sym__newline,
      sym__dedent,
  [1124] = 1,
    ACTIONS(238), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1132] = 1,
    ACTIONS(240), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1140] = 1,
    ACTIONS(242), 5,
      sym__break,
      sym__directive_start,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_identifier,
  [1148] = 3,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(61), 3,
      sym__rule,
      sym_root_rule,
      sym_class_rule,
  [1160] = 4,
    ACTIONS(244), 1,
      aux_sym_directive_value_token1,
    ACTIONS(248), 1,
      sym__indent,
    STATE(20), 1,
      sym_property_value,
    ACTIONS(246), 2,
      sym__newline,
      sym__dedent,
  [1174] = 3,
    ACTIONS(250), 1,
      sym_identifier,
    STATE(35), 1,
      sym_string,
    ACTIONS(252), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [1185] = 3,
    ACTIONS(254), 1,
      sym_identifier,
    STATE(19), 1,
      sym_string,
    ACTIONS(256), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [1196] = 3,
    ACTIONS(258), 1,
      anon_sym_PLUS,
    ACTIONS(260), 1,
      anon_sym_GT,
    STATE(75), 1,
      aux_sym_class_rule_repeat1,
  [1206] = 3,
    ACTIONS(262), 1,
      anon_sym_AT,
    ACTIONS(264), 1,
      anon_sym_GT,
    ACTIONS(266), 1,
      sym_identifier,
  [1216] = 3,
    ACTIONS(258), 1,
      anon_sym_PLUS,
    ACTIONS(268), 1,
      anon_sym_GT,
    STATE(77), 1,
      aux_sym_class_rule_repeat1,
  [1226] = 3,
    ACTIONS(258), 1,
      anon_sym_PLUS,
    ACTIONS(270), 1,
      anon_sym_GT,
    STATE(77), 1,
      aux_sym_class_rule_repeat1,
  [1236] = 3,
    ACTIONS(258), 1,
      anon_sym_PLUS,
    ACTIONS(272), 1,
      anon_sym_GT,
    STATE(74), 1,
      aux_sym_class_rule_repeat1,
  [1246] = 3,
    ACTIONS(274), 1,
      anon_sym_PLUS,
    ACTIONS(277), 1,
      anon_sym_GT,
    STATE(77), 1,
      aux_sym_class_rule_repeat1,
  [1256] = 3,
    ACTIONS(279), 1,
      anon_sym_import,
    ACTIONS(281), 1,
      anon_sym_set,
    ACTIONS(283), 1,
      anon_sym_kivy,
  [1266] = 2,
    ACTIONS(285), 1,
      anon_sym_AT,
    ACTIONS(287), 1,
      anon_sym_GT,
  [1273] = 2,
    ACTIONS(289), 1,
      aux_sym_directive_value_token1,
    STATE(102), 1,
      sym_directive_value,
  [1280] = 2,
    ACTIONS(291), 1,
      sym__newline,
    ACTIONS(293), 1,
      sym__indent,
  [1287] = 2,
    ACTIONS(289), 1,
      aux_sym_directive_value_token1,
    STATE(112), 1,
      sym_directive_value,
  [1294] = 2,
    ACTIONS(244), 1,
      aux_sym_directive_value_token1,
    STATE(18), 1,
      sym_property_value,
  [1301] = 2,
    ACTIONS(232), 1,
      aux_sym_directive_value_token1,
    STATE(41), 1,
      sym_property_value,
  [1308] = 1,
    ACTIONS(295), 2,
      anon_sym_PLUS,
      anon_sym_GT,
  [1313] = 2,
    ACTIONS(297), 1,
      sym__newline,
    ACTIONS(299), 1,
      sym__indent,
  [1320] = 2,
    ACTIONS(289), 1,
      aux_sym_directive_value_token1,
    STATE(110), 1,
      sym_directive_value,
  [1327] = 1,
    ACTIONS(301), 1,
      anon_sym_COLON,
  [1331] = 1,
    ACTIONS(303), 1,
      sym__newline,
  [1335] = 1,
    ACTIONS(305), 1,
      sym_identifier,
  [1339] = 1,
    ACTIONS(307), 1,
      anon_sym_COLON,
  [1343] = 1,
    ACTIONS(309), 1,
      anon_sym__,
  [1347] = 1,
    ACTIONS(311), 1,
      sym_identifier,
  [1351] = 1,
    ACTIONS(313), 1,
      anon_sym_COLON,
  [1355] = 1,
    ACTIONS(315), 1,
      anon_sym_COLON,
  [1359] = 1,
    ACTIONS(317), 1,
      sym_identifier,
  [1363] = 1,
    ACTIONS(319), 1,
      anon_sym_COLON,
  [1367] = 1,
    ACTIONS(321), 1,
      anon_sym_COLON,
  [1371] = 1,
    ACTIONS(323), 1,
      anon_sym_COLON,
  [1375] = 1,
    ACTIONS(325), 1,
      anon_sym_COLON,
  [1379] = 1,
    ACTIONS(327), 1,
      sym_identifier,
  [1383] = 1,
    ACTIONS(329), 1,
      sym__newline,
  [1387] = 1,
    ACTIONS(331), 1,
      anon_sym_COLON,
  [1391] = 1,
    ACTIONS(333), 1,
      ts_builtin_sym_end,
  [1395] = 1,
    ACTIONS(335), 1,
      sym_identifier,
  [1399] = 1,
    ACTIONS(337), 1,
      anon_sym_COLON,
  [1403] = 1,
    ACTIONS(339), 1,
      anon_sym_COLON,
  [1407] = 1,
    ACTIONS(341), 1,
      anon_sym_COLON,
  [1411] = 1,
    ACTIONS(343), 1,
      sym_identifier,
  [1415] = 1,
    ACTIONS(345), 1,
      sym__newline,
  [1419] = 1,
    ACTIONS(347), 1,
      sym__newline,
  [1423] = 1,
    ACTIONS(349), 1,
      sym__newline,
  [1427] = 1,
    ACTIONS(351), 1,
      anon_sym_COLON,
  [1431] = 1,
    ACTIONS(353), 1,
      anon_sym_COLON,
  [1435] = 1,
    ACTIONS(355), 1,
      anon_sym_COLON,
  [1439] = 1,
    ACTIONS(357), 1,
      sym_identifier,
  [1443] = 1,
    ACTIONS(359), 1,
      anon_sym__,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 152,
  [SMALL_STATE(7)] = 190,
  [SMALL_STATE(8)] = 222,
  [SMALL_STATE(9)] = 254,
  [SMALL_STATE(10)] = 286,
  [SMALL_STATE(11)] = 318,
  [SMALL_STATE(12)] = 350,
  [SMALL_STATE(13)] = 382,
  [SMALL_STATE(14)] = 414,
  [SMALL_STATE(15)] = 440,
  [SMALL_STATE(16)] = 466,
  [SMALL_STATE(17)] = 482,
  [SMALL_STATE(18)] = 498,
  [SMALL_STATE(19)] = 516,
  [SMALL_STATE(20)] = 534,
  [SMALL_STATE(21)] = 552,
  [SMALL_STATE(22)] = 567,
  [SMALL_STATE(23)] = 582,
  [SMALL_STATE(24)] = 597,
  [SMALL_STATE(25)] = 612,
  [SMALL_STATE(26)] = 627,
  [SMALL_STATE(27)] = 642,
  [SMALL_STATE(28)] = 657,
  [SMALL_STATE(29)] = 672,
  [SMALL_STATE(30)] = 687,
  [SMALL_STATE(31)] = 702,
  [SMALL_STATE(32)] = 719,
  [SMALL_STATE(33)] = 736,
  [SMALL_STATE(34)] = 753,
  [SMALL_STATE(35)] = 770,
  [SMALL_STATE(36)] = 785,
  [SMALL_STATE(37)] = 798,
  [SMALL_STATE(38)] = 813,
  [SMALL_STATE(39)] = 826,
  [SMALL_STATE(40)] = 843,
  [SMALL_STATE(41)] = 860,
  [SMALL_STATE(42)] = 875,
  [SMALL_STATE(43)] = 892,
  [SMALL_STATE(44)] = 904,
  [SMALL_STATE(45)] = 916,
  [SMALL_STATE(46)] = 928,
  [SMALL_STATE(47)] = 940,
  [SMALL_STATE(48)] = 952,
  [SMALL_STATE(49)] = 964,
  [SMALL_STATE(50)] = 976,
  [SMALL_STATE(51)] = 988,
  [SMALL_STATE(52)] = 1000,
  [SMALL_STATE(53)] = 1015,
  [SMALL_STATE(54)] = 1030,
  [SMALL_STATE(55)] = 1038,
  [SMALL_STATE(56)] = 1046,
  [SMALL_STATE(57)] = 1054,
  [SMALL_STATE(58)] = 1062,
  [SMALL_STATE(59)] = 1070,
  [SMALL_STATE(60)] = 1078,
  [SMALL_STATE(61)] = 1086,
  [SMALL_STATE(62)] = 1094,
  [SMALL_STATE(63)] = 1102,
  [SMALL_STATE(64)] = 1110,
  [SMALL_STATE(65)] = 1124,
  [SMALL_STATE(66)] = 1132,
  [SMALL_STATE(67)] = 1140,
  [SMALL_STATE(68)] = 1148,
  [SMALL_STATE(69)] = 1160,
  [SMALL_STATE(70)] = 1174,
  [SMALL_STATE(71)] = 1185,
  [SMALL_STATE(72)] = 1196,
  [SMALL_STATE(73)] = 1206,
  [SMALL_STATE(74)] = 1216,
  [SMALL_STATE(75)] = 1226,
  [SMALL_STATE(76)] = 1236,
  [SMALL_STATE(77)] = 1246,
  [SMALL_STATE(78)] = 1256,
  [SMALL_STATE(79)] = 1266,
  [SMALL_STATE(80)] = 1273,
  [SMALL_STATE(81)] = 1280,
  [SMALL_STATE(82)] = 1287,
  [SMALL_STATE(83)] = 1294,
  [SMALL_STATE(84)] = 1301,
  [SMALL_STATE(85)] = 1308,
  [SMALL_STATE(86)] = 1313,
  [SMALL_STATE(87)] = 1320,
  [SMALL_STATE(88)] = 1327,
  [SMALL_STATE(89)] = 1331,
  [SMALL_STATE(90)] = 1335,
  [SMALL_STATE(91)] = 1339,
  [SMALL_STATE(92)] = 1343,
  [SMALL_STATE(93)] = 1347,
  [SMALL_STATE(94)] = 1351,
  [SMALL_STATE(95)] = 1355,
  [SMALL_STATE(96)] = 1359,
  [SMALL_STATE(97)] = 1363,
  [SMALL_STATE(98)] = 1367,
  [SMALL_STATE(99)] = 1371,
  [SMALL_STATE(100)] = 1375,
  [SMALL_STATE(101)] = 1379,
  [SMALL_STATE(102)] = 1383,
  [SMALL_STATE(103)] = 1387,
  [SMALL_STATE(104)] = 1391,
  [SMALL_STATE(105)] = 1395,
  [SMALL_STATE(106)] = 1399,
  [SMALL_STATE(107)] = 1403,
  [SMALL_STATE(108)] = 1407,
  [SMALL_STATE(109)] = 1411,
  [SMALL_STATE(110)] = 1415,
  [SMALL_STATE(111)] = 1419,
  [SMALL_STATE(112)] = 1423,
  [SMALL_STATE(113)] = 1427,
  [SMALL_STATE(114)] = 1431,
  [SMALL_STATE(115)] = 1435,
  [SMALL_STATE(116)] = 1439,
  [SMALL_STATE(117)] = 1443,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_canvas_block_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_canvas_block_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_canvas_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_canvas_block_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_canvas_block_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_canvas_block_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_canvas_block_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__rule_body_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_value, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_value, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_binding, 5, 0, 14),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_event_binding, 5, 0, 14),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_declaration, 3, 0, 11),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_declaration, 3, 0, 11),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 12),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 12),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_widget_declaration, 4, 0, 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_widget_declaration, 4, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_binding, 6, 0, 14),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_event_binding, 6, 0, 14),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_canvas_block, 4, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_canvas_block, 4, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_widget_declaration, 3, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_widget_declaration, 3, 0, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_declaration, 4, 0, 11),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_declaration, 4, 0, 11),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__canvas_atom, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__canvas_atom, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_canvas_block, 3, 0, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_canvas_block, 3, 0, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 12),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 12),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_widget_declaration, 5, 0, 1),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_widget_declaration, 5, 0, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_canvas_block, 5, 0, 1),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_canvas_block, 5, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 4, 0, 3),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 5, 0, 7),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 6, 0, 9),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 6, 0, 10),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 7, 0, 13),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_rule, 2, 0, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 8, 0, 13),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_rule, 3, 0, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_directive, 5, 0, 4),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_directive, 5, 0, 5),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_body, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kivy_directive, 4, 0, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 5, 0, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 7, 0, 9),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 7, 0, 10),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_body, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 6, 0, 7),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_rule, 4, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_rule_repeat1, 2, 0, 8), SHIFT_REPEAT(105),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_rule_repeat1, 2, 0, 8),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_rule_repeat1, 2, 0, 6),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [333] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_value, 1, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token__break = 3,
  ts_external_token__directive_start = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__break] = sym__break,
  [ts_external_token__directive_start] = sym__directive_start,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
    [ts_external_token__directive_start] = true,
  },
  [2] = {
    [ts_external_token__break] = true,
    [ts_external_token__directive_start] = true,
  },
  [3] = {
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__break] = true,
    [ts_external_token__directive_start] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
  },
  [8] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_kivy_external_scanner_create(void);
void tree_sitter_kivy_external_scanner_destroy(void *);
bool tree_sitter_kivy_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_kivy_external_scanner_serialize(void *, char *);
void tree_sitter_kivy_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kivy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_kivy_external_scanner_create,
      tree_sitter_kivy_external_scanner_destroy,
      tree_sitter_kivy_external_scanner_scan,
      tree_sitter_kivy_external_scanner_serialize,
      tree_sitter_kivy_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "kivy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
